name: OWASP ZAP Security Scan

on:
  push:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan de sécurité OWASP ZAP

    steps:

      - name: Checkout du code
        uses: actions/checkout@v4

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: 'https://demo.testfire.net'
          fail_action: false
          allow_issue_writing: false

      - name: Upload rapport ZAP
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-rapport
          path: |
            report_html.html
            report_json.json
          retention-days: 7
          if-no-files-found: warn
